### ISSUE TITLE
Getting a 400 Bad Request

### ISSUE THREAD

**Issue by AlphaNeo513** [PegasisForever/Fetch-TA-Data#1]
I'm trying to get data form the api but I'm getting error code 400
Code:

`import requests

payload = {
    "number": "",
    "password": ""
}
p = requests.post('https://api.pegasis.site/public/yrdsb_ta/getmark_v2', data=payload)

print(p)`
For obv reasons, number and password have been removed after testing.

**Comment by PegasisForever** [comment]
p = requests.post('https://api.pegasis.site/public/yrdsb_ta/getmark_v2', **json**=payload)

**Comment by PegasisForever** [comment]
Good to see someone actually using my api :) how did u find it?

**Comment by AlphaNeo513** [comment]
> Good to see someone actually using my api :) how did u find it?

Short answer: Thought of a stupid project, searched up teachassist api on google and found this

Long answer: Got my marks back from a course and while I logged onto teachassist I thought, why not make a TeachAssist discord bot? At first I wanted to make it based on webscraping but instead I typed in TeachAssist api on google and found this.

Btw how is the api getting data from the teachassist?

**Comment by PegasisForever** [comment]
> Btw how is the api getting data from the teachassist?

Simulating a user browsing the ta website, use [jsoup](https://jsoup.org/) to parse HTML.

Btw, ta itself had an official api: https://ta.yrdsb.ca/v4/students/json-20180628.php and https://ta.yrdsb.ca/v4/students/json.php
